import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Star Wars</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <h1>{"Who doesn't love Star Wars"}</h1>

        <Link href={"/CharactersPage"}>Get Character</Link>
      </main>
    </div>
  );
}
